# Generated by Django 2.2 on 2020-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200117_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
