# Generated by Django 2.2 on 2020-01-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_note_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='share',
            new_name='status',
        ),
    ]
